# Generated by Django 2.0.2 on 2018-02-21 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_title', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('clinic_img', models.CharField(max_length=200)),
                ('clinic_detail_1', models.CharField(max_length=500)),
                ('clinic_detail_2', models.CharField(max_length=500)),
                ('clinic_detail_3', models.CharField(max_length=500)),
                ('clinic_detail_4', models.CharField(max_length=500)),
                ('clinic_detail_5', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('coach_img', models.CharField(max_length=200)),
                ('coach_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_url', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('owner_detail_1', models.CharField(max_length=500)),
                ('owner_detail_2', models.CharField(max_length=500)),
                ('owner_detail_3', models.CharField(max_length=500)),
                ('owner_detail_4', models.CharField(max_length=500)),
                ('owner_detail_5', models.CharField(max_length=500)),
                ('owner_detail_6', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('parnter_website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('jersey_number', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('program_img', models.CharField(max_length=200)),
                ('program_detail_1', models.CharField(max_length=500)),
                ('program_detail_2', models.CharField(max_length=500)),
                ('program_detail_3', models.CharField(max_length=500)),
                ('program_detail_4', models.CharField(max_length=500)),
                ('program_detail_5', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('cost', models.CharField(max_length=200)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Clinic')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Location')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('team_description', models.CharField(max_length=1000)),
                ('team_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Team'),
        ),
    ]
