# Generated by Django 2.0.2 on 2018-02-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinic_Title', models.CharField(max_length=200)),
                ('Cost', models.CharField(max_length=200)),
                ('Start_Date', models.DateField(verbose_name='start date')),
                ('End_Date', models.DateField(verbose_name='end date')),
                ('Start_Time', models.TimeField(verbose_name='start time')),
                ('End_Time', models.TimeField(verbose_name='end time')),
                ('Clinic_Image', models.CharField(max_length=200)),
                ('Clinic_Detail_1', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Coach_Image', models.CharField(max_length=200)),
                ('Coach_Bio', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Type', models.CharField(max_length=200)),
                ('Contact_Url', models.CharField(max_length=200)),
                ('Contact_Number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Title', models.CharField(max_length=200)),
                ('Event_Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Name', models.CharField(max_length=200)),
                ('Location_Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Owner_Image', models.CharField(max_length=200)),
                ('Owner_Bio_1', models.TextField(max_length=500)),
                ('Owner_Bio_2', models.TextField(max_length=500)),
                ('Owner_Bio_3', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partner_Name', models.CharField(max_length=200)),
                ('Parnter_Website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Jersey_Number', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Title', models.CharField(max_length=200)),
                ('Cost', models.CharField(max_length=200)),
                ('Start_Date', models.DateField(verbose_name='start date')),
                ('End_Date', models.DateField(verbose_name='end date')),
                ('Program_Image', models.CharField(max_length=200)),
                ('Program_Detail_1', models.TextField(max_length=500)),
                ('Program_Detail_2', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField(verbose_name='start date')),
                ('End_Date', models.DateField(verbose_name='end date')),
                ('Start_Time', models.TimeField(verbose_name='start time')),
                ('End_Time', models.TimeField(verbose_name='end time')),
                ('Cost', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500)),
                ('Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Clinic')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Event')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Location')),
                ('Program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=200)),
                ('Season', models.CharField(max_length=200)),
                ('Team_Description', models.CharField(max_length=1000)),
                ('Team_Image', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='scheduled_event',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Program'),
        ),
        migrations.AddField(
            model_name='player',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels_site.Team'),
        ),
    ]
